### ISSUE TITLE
KeyError: '45bd'

### ISSUE THREAD

**Issue by ailaaila** [happieme/py_innodb_page_info#1]
mysql 版本: 8.0.21 for Win64 on x86_64 (MySQL Community Server - GPL)

**Comment by baiwfg2** [comment]
同问，我也出现了这个
```
 python2 py_innodb_page_info.py /data/mysql-data/db1/t1.ibd 
Total number of page: 7:
Insert Buffer Bitmap: 1
Freshly Allocated Page: 2
File Segment inode: 1
B-tree Node: 1
Traceback (most recent call last):
  File "py_innodb_page_info.py", line 12, in <module>
    mylib.get_innodb_page_type(myargv)
  File "/data/py_innodb_page_info-master/mylib.py", line 72, in get_innodb_page_type
    print "%s: %s"%(innodb_page_type[type],ret[type])
KeyError: '45bd'

```

**Comment by baiwfg2** [comment]
`constexpr page_type_t FIL_PAGE_INDEX = 17855;` ，它为 0x45bf

`constexpr page_type_t FIL_PAGE_SDI = 17853;` ， 它为 0x45bd ，貌似这个type没有被支持
